use std::fs;
use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated.rs");

    let content_dir = Path::new("../content");
    let mut posts: Vec<(String, String, String, String)> = Vec::new();

    for entry in fs::read_dir(content_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let slug = path.file_stem().unwrap().to_str().unwrap().to_string();
        if slug.starts_with('_') {
            continue;
        }
        let raw = fs::read_to_string(&path).unwrap();
        let (title, date, body) = parse_md(&raw);
        posts.push((slug, title, date, body));
    }

    posts.sort_by(|a, b| b.2.cmp(&a.2));

    let mut code = String::from("// generated by build.rs\n\n");
    code.push_str("pub static BLOG_POSTS: &[crate::app::BlogPost] = &[\n");
    for (slug, title, date, body) in &posts {
        let display_date = format_date(date);
        code.push_str("    crate::app::BlogPost {\n");
        code.push_str(&format!("        title: {title:?},\n"));
        code.push_str(&format!("        date: {display_date:?},\n"));
        code.push_str(&format!("        slug: {slug:?},\n"));
        code.push_str(&format!("        body: {body:?},\n"));
        code.push_str("    },\n");
    }
    code.push_str("];\n");

    fs::write(&dest, code.as_bytes()).unwrap();
    println!("cargo:rerun-if-changed=../content");
}

fn format_date(ymd: &str) -> String {
    let months = [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ];
    let parts: Vec<&str> = ymd.split('-').collect();
    if parts.len() == 3 {
        if let (Ok(_y), Ok(m), Ok(d)) = (
            parts[0].parse::<i32>(),
            parts[1].parse::<usize>(),
            parts[2].parse::<i32>(),
        ) {
            if (1..=12).contains(&m) {
                return format!("{} {}, {}", months[m - 1], d, _y);
            }
        }
    }
    ymd.to_string()
}

fn parse_md(content: &str) -> (String, String, String) {
    let mut title = String::new();
    let mut date = String::new();
    let body = if let Some(rest) = content
        .strip_prefix("---\n")
        .or_else(|| content.strip_prefix("---\r\n"))
    {
        if let Some(end) = rest.find("\n---\n").or_else(|| rest.find("\r\n---\r\n")) {
            for line in rest[..end].lines() {
                let line = line.trim();
                if let Some((k, v)) = line.split_once(':') {
                    match k.trim() {
                        "title" => title = v.trim().trim_matches('"').trim_matches('\'').to_string(),
                        "date" => date = v.trim().trim_matches('"').trim_matches('\'').to_string(),
                        _ => {}
                    }
                }
            }
            let body_start = end + 5; // len of "\n---\n"
            rest[body_start..].to_string()
        } else {
            rest.to_string()
        }
    } else {
        content.to_string()
    };
    (title, date, body)
}
