services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "22:22"
    restart: unless-stopped
    networks:
      - dokploy-network

  web:
    image: caddy:alpine
    ports:
      - "80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  caddy_data:
